<head>
    <?php //echo $this->headMeta()->setHttpEquiv('refresh', '5'); ?>
    <?php echo $this->headScript()->prependScript(
            'setTimeout(function(){
                window.location.reload(1);
             }, 60000);'
    ); ?>
</head>
<section id="messages">
    <?php foreach ($this->messageList as $message): ?>
        <div class="message" style="clear: both">
            <span class="msg-time">
                [<?= $this->escapeHtml($message['time']); ?>]
            </span>
            <span class="msg-user">
                <?= $this->escapeHtml($message['user']); ?>:
            </span>
            <span class="msg-message">
                <?= $this->escapeHtml($message['message']); ?>
            </span>
        </div>
    <?php endforeach; ?>
</section>
