<section class="register">
    <h2>Edit file <?= $this->fileName; ?></h2>

    <h3>This file shared to users:</h3>

    <table style="width: 80%;">
        <tr style="border-bottom: 1px solid lightgrey;">
            <th>Name</th>
            <th>Email</th>
            <th>&nbsp</th>
        </tr>

        <?php foreach ($this->sharedUsers as $user): ?>
            <tr style="border-bottom: 1px solid lightgrey;">
                <td style="padding: 5px;"><?= $user->name; ?></td>
                <td style="padding: 5px;"><?= $user->email; ?></td>
                <td style="padding: 5px;">
                    <a href="<?= $this->url(null, ['controller' => 'FileManager', 'action' => 'deleteSharing', 'id' => $this->fileId, 'userId' => $user->id]); ?>" onClick="return confirm('Are you sure you want to delete this user?');">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <h3>Share file to user</h3>
    <?php
    /** @var \Zend\Form\Form $form */
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <dl>
        <?= $this->formLabel($form->get('select')); ?>
    </dl>
    <dd>
        <?= $this->formElement($form->get('select')); ?>
        <?= $this->formElementErrors($form->get('select')); ?>
    </dd>

    <dd>
        <?= $this->formElement($form->get('submit')); ?>
    </dd>

    <?= $this->form()->closeTag(); ?>
</section>
