<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <!-- Meta -->
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->setCharset('utf-8')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('js/jquery-ui-1.12.1/jquery-ui.css'));?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js'), 'text/javascript')
        ; ?>

        <?php echo $this->headScript()->prependScript(
            '$(function() {
            $("a.ui-button").button();
        });', 'text/javascript'
        ); ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('users') ?>"><?php echo $this->translate('Users') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('users/group-chat') ?>"><?php echo $this->translate('Group chat') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('users/email') ?>"><?php echo $this->translate('Send email') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('users/user-manager', ['action' => 'index']); ?>"><?php echo $this->translate('Users manager') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('files/file-manager', ['action' => 'index']); ?>"><?php echo $this->translate('Files manager') ?></a></li>
                        <li class="active"><a href="/time/index"><?php echo $this->translate('Current time') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
